import { chromium } from 'playwright'
import assert from 'node:assert/strict'
import { mkdir, writeFile } from 'node:fs/promises'
await mkdir('preview-assets', { recursive: true })
const browser = await chromium.launch()
const page = await browser.newPage({viewport:{width:1440,height:1100}, deviceScaleFactor:1})
const errors = []
page.on('pageerror', error => errors.push(error.message))
try {
  await page.goto('http://127.0.0.1:4173/preview.html', {waitUntil:'networkidle',timeout:60000})
  await page.locator('.capital-value, .error-state').waitFor({timeout:60000})
  await page.screenshot({path:'preview-assets/desktop.png',fullPage:true})
  assert.equal(await page.locator('.capital-value').count(), 1, 'Live Google Sheet must load; see screenshot if unavailable')
  assert.equal(await page.getByRole('link',{name:'View source sheet'}).getAttribute('href'), 'https://docs.google.com/spreadsheets/d/1Zo7-zIo5SppN4yok494w4ufIuOMIRtFkgxdoXsdpHRo/edit')
  await page.getByRole('link',{name:'Holdings',exact:true}).click()
  await page.getByPlaceholder('Ticker, company, sector, or industry').fill('no-position-match-987654')
  await page.getByText('No holdings match these filters.').waitFor()
  await page.getByPlaceholder('Ticker, company, sector, or industry').fill('')
  await page.locator('.ticker-button').first().click()
  assert.ok(await page.locator('.detail-panel').isVisible())
  await page.locator('.compare-toggle').nth(0).click()
  await page.locator('.compare-toggle').nth(1).click()
  await page.getByRole('button',{name:'Compare holdings',exact:true}).click()
  await page.getByRole('dialog',{name:'Compare holdings'}).waitFor()
  await page.getByRole('button',{name:'Close comparison'}).focus()
  await page.keyboard.press('Escape')
  await page.getByRole('dialog').waitFor({state:'detached'})
  await page.getByRole('link',{name:'Research',exact:true}).click()
  await page.getByText('Better questions. Better decisions.').waitFor()
  await page.getByRole('link',{name:'Benchmark',exact:true}).click()
  await page.getByText('Conviction in context.').waitFor()
  await page.getByRole('link',{name:'Overview',exact:true}).click()
  await page.setViewportSize({width:390,height:844})
  await page.screenshot({path:'preview-assets/mobile.png',fullPage:true})
  await page.screenshot({path:'preview-assets/mobile-viewport.png',fullPage:false})
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth <= window.innerWidth), 'Mobile layout must fit the screen')
  await page.getByRole('link',{name:'Holdings',exact:true}).click()
  await page.locator('.ticker-button').first().click()
  await page.locator('.detail-panel.open').waitFor()
  await page.getByRole('button',{name:'Close holding details'}).click()
  await page.locator('.detail-panel.open').waitFor({state:'detached'})
  assert.deepEqual(errors,[], 'No browser runtime errors')
  await page.setViewportSize({width:1440,height:1100})
  await page.goto('https://htmlpreview.github.io/?https://raw.githubusercontent.com/QualisArtifex1/FinanceClubHoldings/codex/premium-redesign/preview.html', {waitUntil:'networkidle',timeout:60000})
  await page.locator('.capital-value').waitFor({timeout:60000})
  await page.screenshot({path:'preview-assets/hosted-preview.png',fullPage:false})
  assert.ok(await page.locator('.capital-value').isVisible(), 'Hosted preview must render live data')
  await writeFile('preview-assets/checks.json', JSON.stringify({passed:true,checks:['Live Google Sheet','Original sheet link','Holdings search','Holding details','Two-position comparison','Keyboard dismissal','Research and benchmark navigation','Mobile viewport','Mobile detail dismissal','No runtime errors']},null,2))
} finally {
  await browser.close()
}
